/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

export enum ConnectionTypeEnum {
  Snowflake = "snowflake",
  Bigquery = "bigquery",
  Redshift = "redshift",
  Mongodb = "mongodb",
  Webhook = "webhook",
}
