/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Successfully created link token
 */
export class CreateLinkTokenResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "link_token" })
  linkToken?: string;
}
