/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

export enum FieldTypeEnum {
  String = "string",
  Integer = "integer",
  Timestamp = "timestamp",
  Json = "json",
  Boolean = "boolean",
}
