/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

export enum FrequencyUnitsEnum {
  Minutes = "minutes",
  Hours = "hours",
  Days = "days",
  Weeks = "weeks",
}
