/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ObjectField } from "./objectfield";
import { Expose, Type } from "class-transformer";

export class ObjectT extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "destination_id" })
  destinationId?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "display_name" })
  displayName?: string;

  /**
   * This is where Fabra will insert the End Customer ID specified in the sync configuration
   */
  @SpeakeasyMetadata()
  @Expose({ name: "end_customer_id_field" })
  endCustomerIdField?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "namespace" })
  namespace?: string;

  @SpeakeasyMetadata({ elemType: ObjectField })
  @Expose({ name: "object_fields" })
  @Type(() => ObjectField)
  objectFields?: ObjectField[];

  @SpeakeasyMetadata()
  @Expose({ name: "table_name" })
  tableName?: string;
}
