/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

/**
 * Successfully fetched destinations
 */
export class GetDestinations200ApplicationJSON extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: shared.Destination })
  @Expose({ name: "destinations" })
  @Type(() => shared.Destination)
  destinations?: shared.Destination[];
}

export class GetDestinationsResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Successfully fetched destinations
   */
  @SpeakeasyMetadata()
  getDestinations200ApplicationJSONObject?: GetDestinations200ApplicationJSON;
}
