/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Type } from "class-transformer";

export class GetNamespacesQueryParams extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=connectionID",
  })
  connectionID: number;
}

export class GetNamespacesRequest extends SpeakeasyBase {
  @SpeakeasyMetadata()
  queryParams: GetNamespacesQueryParams;
}

export class GetNamespacesResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Successfully fetched namespaces
   */
  @SpeakeasyMetadata()
  namespaces?: shared.Namespaces;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
