/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

/**
 * Successfully fetched sources
 */
export class GetSources200ApplicationJSON extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: shared.Source })
  @Expose({ name: "sources" })
  @Type(() => shared.Source)
  sources?: shared.Source[];
}

export class GetSourcesResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Successfully fetched sources
   */
  @SpeakeasyMetadata()
  getSources200ApplicationJSONObject?: GetSources200ApplicationJSON;
}
