/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

/**
 * Successfully fetched syncs
 */
export class GetSyncs200ApplicationJSON extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: shared.Sync })
  @Expose({ name: "syncs" })
  @Type(() => shared.Sync)
  syncs?: shared.Sync[];
}

export class GetSyncsResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Successfully fetched syncs
   */
  @SpeakeasyMetadata()
  getSyncs200ApplicationJSONObject?: GetSyncs200ApplicationJSON;
}
